version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - ls
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - app.js
    - node_modules/
    - src/
    - package.json
