version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - pwd
      - cp -R src/ var/app/current/
      - ls
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - app.js
    - package.json
    - package-lock.json
    - src/**
    - public/**
    - config/**
    - .env
    - node_modules/**/*
    - dist/**/*
  discard-paths: yes
