version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - pwd
      - ls
  post_build:
    commands:
      - echo Build completed on `date`
      - zip -r my-node-app.zip .

artifacts:
  files:
    - my-node-app.zip
  discard-paths: yes
